name = input("What's your name?: ")
myFood = input("What's your favourite food: ")
music = input("What's your favourite music? ")
place = input("Where do you live?: ")
print("you are")
print(name)
print("You're probably hungry for")
print(myFood)
print("and you're definitely getting your groove on to")
print(music)
print("Living in the amazing")
print(place)
