like = input("What's your favorite food? ")
hate = input("What's your least favorite topping?")
print("Your favorite food is ", like, " and your least favorite topping is ", hate, ".")
print("You are a ", like, " and ", hate, " person.")
name = input("What is your name?")
enemy = input("What is your enemy's name?")
superpower = input("What is your superpower?")
print("Your name is ", name, " and your enemy's name is ", enemy, " and your superpower is ", superpower, ".")
print("I love what you have.")